const audioUrls = {
  // fr: "https://soundcloud.com/d-it-m/b1445-934328548?si=a4127526ddc441098c630c5f91a97551&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  // ha: "",
  // sw: "",
  // am: "",
  // ml: "",
  //////////////////
  mn: "https://soundcloud.com/d-it-m/1445a?si=6681ed28fddb4f1ab49762c0d689d5c2&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  bh: "https://soundcloud.com/d-it-m/1445a-1?si=25bdd003aa42407da4a6528023972435&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  uz: "https://soundcloud.com/d-it-m/1445a-2?si=b9e6f7635bbc4437a33346db85d1b4a6&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  ps: "https://soundcloud.com/d-it-m/1445a-3?si=80aba79beb13450787e3db70c0ab53bb&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  af_fa:
    "https://soundcloud.com/d-it-m/1445a-4?si=d30ee6df65b345f99ee017ea2ac959ca&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  hi: "https://soundcloud.com/d-it-m/1445a-5?si=d30ee6df65b345f99ee017ea2ac959ca&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  pa: "https://soundcloud.com/d-it-m/1445a-6?si=6fe954af6ee546a28b3e4daba7e5c195&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  sd: "https://soundcloud.com/d-it-m/1445a-7?si=7f39aebacb71415b922bdb4da4b6dfab&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  // fa: "https://soundcloud.com/d-it-m/1445a-8?si=2f3effb5f5a34961a975bd0c8edcd85f&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  // bs: "https://soundcloud.com/d-it-m/1445a-9?si=577697a0d6dc4e26bb30cf646f7470f6&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  // ur: "https://soundcloud.com/d-it-m/1445a-10?si=870a4c4656fb47aeaadad8fd8054217a&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  // tl: "https://soundcloud.com/d-it-m/1445a1?si=9751df40af2a441d914ef61288288efd&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  ja: "https://soundcloud.com/d-it-m/1445a2?si=0ae2cff3f87a49ef96f2410e3032ecad&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  ko: "https://soundcloud.com/d-it-m/1445a3?si=32e026537d1b44c1804f4b2bde52f74f&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  // id: "https://soundcloud.com/d-it-m/1445a4?si=5551f4c3a67e4455a03672b31916c01b&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  // ms: "https://soundcloud.com/d-it-m/1445a5?si=d82b78c1ee8b4a0bb4bef681b5f01c31&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  // pt: "https://soundcloud.com/d-it-m/1445a6?si=882233d01a9041c8bdf587b7dc1aa91e&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  // es: "https://soundcloud.com/d-it-m/1445a7?si=9f203f6a66a04e9288e9faf52a11f4aa&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  // en: "https://soundcloud.com/d-it-m/1445a8?si=bd044edb75d0417c9506897f9183429e&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  ak: "https://soundcloud.com/d-it-m/1445a9?si=488d181f63c0483bb48d3a30b6f86210&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  // de: "https://soundcloud.com/d-it-m/1445-389069820?si=99a7329d18cb45c29510a2febda35856&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  ff: "https://soundcloud.com/ahmed-magdi-217/2c7dteaxp5la",
  // tr: "https://soundcloud.com/d-it-m/1445-703912414?si=4a53e788fa894d34b8cc4096517fc0ea&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  nl: "https://soundcloud.com/d-it-m/1445-806011714?si=cbda5b456f08454da4a4f378474d6c98&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  so: "https://soundcloud.com/d-it-m/1445-518245242?si=94867d6675bc43f8a19416c4655257de&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  // ru: "https://soundcloud.com/d-it-m/1445-320435797?si=f13b41e11b9e420a9fc2a5df537043fb&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  // zh: "https://soundcloud.com/d-it-m/1445-291017483?si=7288194d8b5f45b594bc3465116e5fea&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  sv: "https://soundcloud.com/d-it-m/1445-175513555?si=a6be601dc07d470e86a2249c672863ea&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  ne: "https://soundcloud.com/d-it-m/1445-901483053?si=4b78837f8e1940c6b812d3c6033e3249&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  th: "https://soundcloud.com/d-it-m/1445-947569984?si=98aca783efaf407bb726ce652071c615&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
  // it: "https://soundcloud.com/d-it-m/1445-864443675?si=1cc28615bc9f4011abdedd6d3ae21de6&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
};

export const videoData = {
  en: {
    videoId: "-7rGUVF4tdg",
    title: "English ",
    videoTitle: "Arafah Sermon",
    script: "",
    flag: "https://flagcdn.com/us.svg",
    audio: audioUrls.en,
    counters: {
      total: "Total Visitors",
      language: "Visitors for English",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  es: {
    videoId: "NaUTLvP_IvA",
    title: "Spanish ",
    videoTitle: "Sermón de Arafat",
    script: "",
    flag: "https://flagcdn.com/es.svg",
    audio: audioUrls.es,
    counters: {
      total: "Total de Visitantes",
      language: "Visitantes para Español",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  fr: {
    videoId: "IrkpAW2e68M",
    title: "French ",
    videoTitle: "Sermon d'Arafat",
    script: "",
    flag: "https://flagcdn.com/fr.svg",
    audio: audioUrls.fr,
    counters: {
      total: "Total des Visiteurs",
      language: "Visiteurs pour Français",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  de: {
    videoId: "TujYnAxhGSY",
    title: "German ",
    videoTitle: "Arafat-Predigt",
    script: "",
    flag: "https://flagcdn.com/de.svg",
    audio: audioUrls.de,
    counters: {
      total: "Gesamt Besucher",
      language: "Besucher für Deutsch",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  it: {
    videoId: "mxZgR8jrfQI",
    title: "Italian ",
    videoTitle: "Sermone di Arafat",
    script: "",
    flag: "https://flagcdn.com/it.svg",
    audio: audioUrls.it,
    counters: {
      total: "Visitatori Totali",
      language: "Visitatori per Italiano",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  pt: {
    videoId: "79i5d7S97iA",
    title: "Portuguese ",
    videoTitle: "Sermão de Arafat",
    script: "",
    flag: "https://flagcdn.com/pt.svg",
    audio: audioUrls.pt,
    counters: {
      total: "Total de Visitantes",
      language: "Visitantes para Português",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  bn: {
    videoId: "zqfcdSv6aDg",
    title: "Bengali ",
    videoTitle: "আরাফাতের খুৎবা",
    script: "",
    flag: "https://flagcdn.com/bd.svg",
    audio: audioUrls.bn,
    counters: {
      total: "মোট দর্শক",
      language: "বাংলার দর্শক",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  ru: {
    videoId: "Gd3n8xOE1gA",
    title: "Russian ",
    videoTitle: "Проповедь Арафата",
    script: "",
    flag: "https://flagcdn.com/ru.svg",
    audio: audioUrls.ru,
    counters: {
      total: "Всего Посетителей",
      language: "Посетители для Русский",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  zh: {
    videoId: "WPxnq9iLj0I",
    title: "Chinese ",
    videoTitle: "阿拉法讲道",
    script: "",
    flag: "https://flagcdn.com/cn.svg",
    audio: audioUrls.zh,
    counters: {
      total: "总访客数",
      language: "访客为 中文",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  ja: {
    videoId: "euKAfb0dTPk",
    title: "Japanese ",
    videoTitle: "アラファ説教",
    script: "",
    flag: "https://flagcdn.com/jp.svg",
    audio: audioUrls.ja,
    counters: {
      total: "総訪問者数",
      language: "訪問者 日本語",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  ko: {
    videoId: "euKAfb0dTPk",
    title: "Korean ",
    videoTitle: "아라파 설교",
    script: "",
    flag: "https://flagcdn.com/kr.svg",
    audio: audioUrls.ko,
    counters: {
      total: "총 방문자 수",
      language: "방문자 한국어",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  ar: {
    videoId: "euKAfb0dTPk",
    title: "Arabic ",
    videoTitle: "خطبة عرفة",
    script: "خطبة عرفة",
    flag: "https://flagcdn.com/sa.svg",
    audio: null,
    counters: {
      total: "إجمالي الزوار",
      language: "الزوار لـ عربي",
    },
  },
  hi: {
    videoId: "euKAfb0dTPk",
    title: "Hindi ",
    videoTitle: "अराफात का प्रवचन",
    script: "",
    flag: "https://flagcdn.com/in.svg",
    audio: audioUrls.hi,
    counters: {
      total: "कुल आगंतुक",
      language: "आगंतुक हिंदी के लिए",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  tr: {
    videoId: "hH8RQtGw04I",
    title: "Turkish ",
    videoTitle: "Arafat Vaazı",
    script: "",
    flag: "https://flagcdn.com/tr.svg",
    audio: audioUrls.tr,
    counters: {
      total: "Toplam Ziyaretçi",
      language: "Türkçe Ziyaretçiler",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  nl: {
    videoId: "euKAfb0dTPk",
    title: "Dutch ",
    videoTitle: "Arafat Preek",
    script: "",
    flag: "https://flagcdn.com/nl.svg",
    audio: audioUrls.nl,
    counters: {
      total: "Totaal Bezoekers",
      language: "Bezoekers voor Nederlands",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  sv: {
    videoId: "euKAfb0dTPk",
    title: "Swedish ",
    videoTitle: "Arafat Predikan",
    script: "",
    flag: "https://flagcdn.com/se.svg",
    audio: audioUrls.sv,
    counters: {
      total: "Totalt Besökare",
      language: "Besökare för Svenska",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  th: {
    videoId: "euKAfb0dTPk",
    title: "Thai ",
    videoTitle: "คำเทศนาอาราฟะ",
    script: "",
    flag: "https://flagcdn.com/th.svg",
    audio: audioUrls.th,
    counters: {
      total: "จำนวนผู้เข้าชมทั้งหมด",
      language: "ผู้เข้าชมสำหรับภาษาไทย",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },

  id: {
    videoId: "haiS6MQnjMw",
    title: "Indonesian ",
    videoTitle: "Khutbah Arafat",
    script: "",
    flag: "https://flagcdn.com/id.svg",
    audio: audioUrls.id,
    counters: {
      total: "Total Pengunjung",
      language: "Pengunjung untuk Bahasa Indonesia",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  ml: {
    videoId: "4OZws7FyJB4",
    title: "Malayalam ",
    videoTitle: "അറഫത്ത് പ്രഭാഷണം",
    script: "",
    flag: "https://flagcdn.com/in.svg",
    audio: audioUrls.ml,
    counters: {
      total: "ആകെ സന്ദർശകർ",
      language: "മലയാള സന്ദർശകർ",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  ms: {
    videoId: "w6kQ-ZfDsMo",
    title: "Malay ",
    videoTitle: "Khutbah Arafah",
    script: "",
    flag: "https://flagcdn.com/my.svg",
    audio: audioUrls.ms,
    counters: {
      total: "Jumlah Pengunjung",
      language: "Pengunjung untuk Bahasa Melayu",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  fa: {
    videoId: "XHpVdfoRyuM",
    title: "Persian ",
    videoTitle: "خطبه عرفات",
    script: "",
    flag: "https://flagcdn.com/ir.svg",
    audio: audioUrls.fa,
    counters: {
      total: "تعداد کل بازدیدکنندگان",
      language: "بازدیدکنندگان برای فارسی",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  ur: {
    videoId: "ktf9cP7pCIU",
    title: "Urdo ",
    videoTitle: "خطبہ عرفات",
    script: "",
    flag: "https://flagcdn.com/pk.svg",
    audio: audioUrls.ur,
    counters: {
      total: "کل زائرین",
      language: "اردو کے لئے زائرین",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  pa: {
    videoId: "euKAfb0dTPk",
    title: "Punjabi ",
    videoTitle: "ਅਰਫਾਤ ਦਾ ਉਪਦੇਸ਼",
    script: "",
    flag: "https://flagcdn.com/in.svg",
    audio: audioUrls.pa,
    counters: {
      total: "ਕੁੱਲ ਵਿਜ਼ਟਰਜ਼",
      language: "ਪੰਜਾਬੀ ਲਈ ਵਿਜ਼ਟਰਜ਼",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  sw: {
    videoId: "v8km0IPPGoA",
    title: "Swahili ",
    videoTitle: "Mahubiri ya Arafat",
    script: "",
    flag: "https://flagcdn.com/ke.svg",
    audio: audioUrls.sw,
    counters: {
      total: "Wageni Wote",
      language: "Wageni kwa Kiswahili",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  am: {
    videoId: "vn_HGzqxJag",
    title: "Amharic ",
    videoTitle: "የአራፋ ስብከት",
    script: "",
    flag: "https://flagcdn.com/et.svg",
    audio: audioUrls.am,
    counters: {
      total: "ጠቅላላ ጎብኝዎች",
      language: "እንግዶች አማርኛ ላይ",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  uz: {
    videoId: "euKAfb0dTPk",
    title: "Uzbek ",
    videoTitle: "Arofat vaʼzi",
    script: "",
    flag: "https://flagcdn.com/uz.svg",
    audio: audioUrls.uz,
    counters: {
      total: "Jami Tashrifchilar",
      language: "Oʻzbek Tilidagi Tashrifchilar",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  mn: {
    videoId: "euKAfb0dTPk",
    title: "Mandinka ",
    videoTitle: "Arafah Sermon",
    script: "",
    flag: "https://flagcdn.com/gm.svg",
    audio: audioUrls.mn,
    counters: {
      total: "Total Visitors",
      language: "Visitors for Mandinka",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  ne: {
    videoId: "euKAfb0dTPk",
    title: "Nepali ",
    videoTitle: "अराफात प्रवचन",
    script: "",
    flag: "https://flagcdn.com/np.svg",
    audio: audioUrls.ne,
    counters: {
      total: "कुल आगन्तुक",
      language: "नेपालीका लागि आगन्तुक",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  tl: {
    videoId: "uoPoQGXqfas",
    title: "Tagalog ",
    videoTitle: "Sermon ng Arafat",
    script: "",
    flag: "https://flagcdn.com/ph.svg",
    audio: audioUrls.tl,
    counters: {
      total: "Kabuuang Mga Bisita",
      language: "Mga Bisita para sa Tagalog",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  ha: {
    videoId: "6AuwLo51eeg",
    title: "Hausa ",
    videoTitle: "Huduba ta Arafat",
    script: "",
    flag: "https://flagcdn.com/ng.svg",
    audio: audioUrls.ha,
    counters: {
      total: "Jimillar Baƙi",
      language: "Baƙi don Hausa",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  ak: {
    videoId: "euKAfb0dTPk",
    title: "Akan ",
    videoTitle: "Arafah Sermon",
    script: "",
    flag: "https://flagcdn.com/gh.svg",
    audio: audioUrls.ak,
    counters: {
      total: "Total Visitors",
      language: "Visitors for Akan",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  bh: {
    videoId: "euKAfb0dTPk",
    title: "Bhojpuri ",
    videoTitle: "Arafah Sermon",
    script: "",
    flag: "https://flagcdn.com/in.svg",
    audio: audioUrls.bh,
    counters: {
      total: "Total Visitors",
      language: "Visitors for Bhojpuri",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  ps: {
    videoId: "euKAfb0dTPk",
    title: "Pashto ",
    videoTitle: "Arafah Sermon",
    script: "",
    flag: "https://flagcdn.com/af.svg",
    audio: audioUrls.ps,
    counters: {
      total: "Total Visitors",
      language: "Visitors for Pashto",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  af_fa: {
    videoId: "euKAfb0dTPk",
    title: "Afghan Persian ",
    videoTitle: "خطبه عرفات",
    script: "",
    flag: "https://flagcdn.com/af.svg",
    audio: audioUrls.af_fa,
    counters: {
      total: "تعداد کل بازدیدکنندگان",
      language: "بازدیدکنندگان برای فارسی دری",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  ff: {
    videoId: "euKAfb0dTPk",
    title: "Fula ",
    videoTitle: "Sermon d'Arafat",
    script: "",
    flag: "https://flagcdn.com/sn.svg",
    audio: audioUrls.ff,
    counters: {
      total: "Heɓooji Jumɗo",
      language: "Heɓooji Pulaar",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  so: {
    videoId: "euKAfb0dTPk",
    title: "Somali ",
    videoTitle: "Khudbadii Carafo",
    script: "",
    flag: "https://flagcdn.com/so.svg",
    audio: audioUrls.so,
    counters: {
      total: "Booqdayaasha Guud",
      language: "Booqdayaasha Af-Soomaaliga",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  sd: {
    videoId: "euKAfb0dTPk",
    title: "Sindhi ",
    videoTitle: "عرفات جو خطبو",
    script: "",
    flag: "https://flagcdn.com/pk.svg",
    audio: audioUrls.sd,
    counters: {
      total: "ڪل زائرين",
      language: "سنڌي لاءِ زائرين",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
  bs: {
    videoId: "ZnciaX9J6hw",
    title: "Bosnian ",
    videoTitle: "Arafatska hutba",
    script: "",
    flag: "https://flagcdn.com/ba.svg",
    audio: audioUrls.bs,
    counters: {
      total: "Ukupno posjetitelja",
      language: "Posjetitelji za Bosanski",
    },
    syncMessage: "The video is not synced with the translation voice.",
  },
};
